name: bid_client

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.6.15"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  google_fonts: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bid_mock.json


